# Generated by Django 3.2.2 on 2021-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
